<?php

$string = "[
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1599224578,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"_ga\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"GA1.2.1894494671.1536152578\",
    \"id\": 1
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1536238978,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"_gid\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"GA1.2.716004836.1536152578\",
    \"id\": 2
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1570316578,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"cto_lwid\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"eb61b1fe-43a6-41bf-8890-89761a9e956a\",
    \"id\": 3
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1693832999.748274,
    \"hostOnly\": false,
    \"httpOnly\": true,
    \"name\": \"gt_ab\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"rn:NDUw\",
    \"id\": 4
},
{
    \"domain\": \".gumtree.com\",
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"gt_adconsent\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": true,
    \"storeId\": \"0\",
    \"value\": \"mod:MQ==|state:Mg==\",
    \"id\": 5
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1538744999.748797,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"gt_appBanner\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"actionTriggered:TWVzc2FnZUNlbnRlcldlYkFwcA==|appBannerVisible:dHJ1ZQ==|bannerViewCount:MQ==\",
    \"id\": 6
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1693832617.253008,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"gt_mc\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"rcd:MA==|nuc:MA==\",
    \"id\": 7
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1693832999.74848,
    \"hostOnly\": false,
    \"httpOnly\": true,
    \"name\": \"gt_p\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"id:OGY0MTk3YTktN2E3My00NWQzLThhZGEtMzM2NmJhMWYwYmQ5\",
    \"id\": 8
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1567688617.252876,
    \"hostOnly\": false,
    \"httpOnly\": true,
    \"name\": \"gt_rememberMe\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"5gZw1FKKSHq9tAbO1GBWFQHk+oToVZN7/dY+iWn+BBbkSAAb4o+jiAx3l9d7FmFsPWc2CKlCESdLyKZbAnasqEqtQpHvT0SI8kNgFfi9jvIORThHZQCC7gPZ5/g8C3u8r7Z+/kAKRF++eiywN3IQfv5BHZ3HanAMFZeIh4sKd8YRyGPgIGsJXzpNqQoTGa55nhoJ7XjbC/949WMr1al3vkQQ+JmkUmTKK5tjB6M3bG30bspbsPMcO1q5L4QF/2a6U3XDJVqobecM9i2dQFLauP2Xw1Ebhml4I1ZFB+r2E8Yd9NKlYOK936Y1wNa8vxAgQ5UZV1PR1USQCwRsLZjNL2JUHHVZS04T/F+bpRhOrWCsmUwuFYF399JK3z/aCI1WxINvgQG7hLO7WRVxgUd4P21W3tWxhnqa6Ndx3V20QLSaJdVUDOPXSGxy65yCzPKxP275MdISHTeXsOEGBBSH+9DCSve+TWCL1/jspKnuo/W4FDY3RWbPRm/jOKsCeK4Kw62pgypBnk6h73Nd3iu9ai/TNjAbvHeog1eIFpH/SSCB4jbG7ZgWp11cyvMTaBGfD84teqcH//n2R5lO3z4DZWVGBjf4MEXo+wx6viKnc5h0J3QHKWYFRpiAds6dKpmE\",
    \"id\": 9
},
{
    \"domain\": \".gumtree.com\",
    \"hostOnly\": false,
    \"httpOnly\": true,
    \"name\": \"gt_s\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": true,
    \"storeId\": \"0\",
    \"value\": \"id:OXk1OHJpOWFteGFmd2tscHcwaG1uN2hm\",
    \"id\": 10
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1693832547.439874,
    \"hostOnly\": false,
    \"httpOnly\": true,
    \"name\": \"gt_tm\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"ef47b209-e5b1-4716-9942-d7b35873130f\",
    \"id\": 11
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1693832999.748672,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"gt_userPref\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"isSearchOpen:dHJ1ZQ==|recentAdsOne:Y2Fycy12YW5zLW1vdG9yYmlrZXM=|cookiePolicy:dHJ1ZQ==|recentAdsTwo:Zm9yLXNhbGU=|location:dWs=\",
    \"id\": 12
},
{
    \"domain\": \".gumtree.com\",
    \"expirationDate\": 1551705036,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"optimizelyEndUserId\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"oeu1536148972915r0.3050435842952002\",
    \"id\": 13
},
{
    \"domain\": \".my.gumtree.com\",
    \"expirationDate\": 1599225037,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"_ga\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"GA1.3.1182307061.1536148973\",
    \"id\": 14
},
{
    \"domain\": \".my.gumtree.com\",
    \"expirationDate\": 1536239437,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"_gid\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"GA1.3.1907996772.1536148973\",
    \"id\": 15
},
{
    \"domain\": \".my.gumtree.com\",
    \"expirationDate\": 1536239438,
    \"hostOnly\": false,
    \"httpOnly\": false,
    \"name\": \"gt_mc\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"\\"rcd:MTUzNjE1MzQ1Nzk0OA ==|nuc:MA == \\"\",
    \"id\": 16
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1538781038.822823,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"D_HID\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"A507493D-0C9E-353C-BB2C-C264C2681F01\",
    \"id\": 17
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1538781038.82265,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"D_IID\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"D16C763F-A159-332D-B51D-CC2A6A6DBB99\",
    \"id\": 18
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1567684974.582788,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"D_SID\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"197.14.48.119:yrfhk6sda+/XhpdPOIvye94Qy5T71UyzsBHdrgxxryY\",
    \"id\": 19
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1538781038.822708,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"D_UID\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"B9910C16-C859-3CFA-8516-66342A151527\",
    \"id\": 20
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1538781038.822747,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"D_ZID\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"D92C192C-60F2-3A82-A6C1-2327582C5C8B\",
    \"id\": 21
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1538781038.822787,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"D_ZUID\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"12ACF17E-606C-3938-AA1C-368A2D2A7A3A\",
    \"id\": 22
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1536156139.774285,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"GTSELLERSESSIONID\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"9y58ri9amxafwklpw0hmn7hf\",
    \"id\": 23
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1693919438,
    \"hostOnly\": true,
    \"httpOnly\": false,
    \"name\": \"ki_t\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"1536148977039%3B1536148977039%3B1536153038863%3B1%3B8\",
    \"id\": 24
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1851772166,
    \"hostOnly\": true,
    \"httpOnly\": false,
    \"name\": \"liveagent_oref\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"https://my.gumtree.com/manage/ads\",
    \"id\": 25
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1851772166,
    \"hostOnly\": true,
    \"httpOnly\": false,
    \"name\": \"liveagent_ptid\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"0cc5db10-53fc-4e20-85bb-5ed18d1ea99c\",
    \"id\": 26
},
{
    \"domain\": \"my.gumtree.com\",
    \"hostOnly\": true,
    \"httpOnly\": false,
    \"name\": \"liveagent_sid\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": true,
    \"storeId\": \"0\",
    \"value\": \"0cc5db10-53fc-4e20-85bb-5ed18d1ea99c\",
    \"id\": 27
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1851772166,
    \"hostOnly\": true,
    \"httpOnly\": false,
    \"name\": \"liveagent_vc\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": false,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"2\",
    \"id\": 28
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1536235444.218264,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"NSC_dmpve_tfmmfsqppm\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"30dfa3db00a265bfba5de9b0f0e8b2e5a753267eb4a0c78623104733c165719661953c78\",
    \"id\": 29
},
{
    \"domain\": \"my.gumtree.com\",
    \"expirationDate\": 1536239402.418204,
    \"hostOnly\": true,
    \"httpOnly\": true,
    \"name\": \"NSC_dmpve_vtfsqppm-fti\",
    \"path\": \"/\",
    \"sameSite\": \"no_restriction\",
    \"secure\": true,
    \"session\": false,
    \"storeId\": \"0\",
    \"value\": \"14b5a3d964a07877227fe40585f1f28a4af1b1a4c1469a995d67387638ad95dcdb320a0d\",
    \"id\": 30
}
]
";

$json_a = json_decode($string, true);
$string="Cookie: ";
for($i=0;$i<count($json_a);$i++){

    $string.= $json_a[$i]['name'].'='.$json_a[$i]['value']."; ";
}

return [
    'string' => $string
];